import asyncio
from database.db import async_session, init_db
from database.models import StaticResult
from sqlalchemy import select

SEED_DATA = [
    {
        "experiment": "Exp 1",
        "dbms": "SQLite",
        "version": "3.49.1",
        "oracle": "TLP WHERE",
        "total_queries": 1840446,
        "throughput_qps": 16239,
        "success_rate": 0.98,
        "bugs_found": 1,
        "bug_type": "Logic Bug",
        "observations": "BETWEEN+QUOTE()/view: 1 vs 0 rows.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "SQLite",
        "version": "3.49.1",
        "oracle": "TLP GROUP BY",
        "total_queries": 5382286,
        "throughput_qps": 12926,
        "success_rate": 0.98,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. Stable throughput.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "SQLite",
        "version": "3.49.1",
        "oracle": "TLP AGGREGATE",
        "total_queries": 275961,
        "throughput_qps": 3067,
        "success_rate": 0.55,
        "bugs_found": 1,
        "bug_type": "Logic Bug",
        "observations": "MAX(CHAR) with UTF-16 + FTS5: incorrect result.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "SQLite",
        "version": "3.49.1",
        "oracle": "NoREC",
        "total_queries": 7809486,
        "throughput_qps": 15601,
        "success_rate": 0.96,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. Highest throughput in SQLite.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "MySQL",
        "version": "8.0.46",
        "oracle": "TLP WHERE",
        "total_queries": 509162,
        "throughput_qps": 5598,
        "success_rate": 0.99,
        "bugs_found": 2,
        "bug_type": "Logic Bug",
        "observations": "2 bugs: boolean predicate concatenation + IF(NULL).",
    },
    {
        "experiment": "Exp 1",
        "dbms": "MySQL",
        "version": "8.0.46",
        "oracle": "PQS",
        "total_queries": 966303,
        "throughput_qps": 2893,
        "success_rate": 0.99,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs with PQS.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "TiDB",
        "version": "latest",
        "oracle": "TLP WHERE",
        "total_queries": 1214240,
        "throughput_qps": 3554,
        "success_rate": 0.45,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. Low success rate (45%).",
    },
    {
        "experiment": "Exp 1",
        "dbms": "PostgreSQL",
        "version": "15.17",
        "oracle": "NoREC",
        "total_queries": 225475,
        "throughput_qps": 605,
        "success_rate": 0.33,
        "bugs_found": 0,
        "bug_type": "Eroare Instrumentare",
        "observations": "NullPointerException SQLancer. Incompatible with PG 15.x.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "PostgreSQL",
        "version": "15.17",
        "oracle": "TLP WHERE",
        "total_queries": 135140,
        "throughput_qps": 316,
        "success_rate": 0.59,
        "bugs_found": 0,
        "bug_type": "Eroare Instrumentare",
        "observations": "25 stopped threads. Invalid results.",
    },
    {
        "experiment": "Exp 1",
        "dbms": "CockroachDB",
        "version": "13.0.0",
        "oracle": "N/A",
        "total_queries": 0,
        "throughput_qps": 0,
        "success_rate": 0,
        "bugs_found": 0,
        "bug_type": "Instrumentation Not Supported",
        "observations": "Setting eliminated in v13. Incompatible with SQLancer 2.0.0.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "TiDB",
        "version": "latest",
        "oracle": "TLP HAVING",
        "total_queries": 359864,
        "throughput_qps": 1152,
        "success_rate": 0.53,
        "bugs_found": 13,
        "bug_type": "Logic Bug (HAVING)",
        "observations": "13 bugs: content mismatch (x9) + size mismatch (x4). NATURAL RIGHT JOIN + GROUP BY + HAVING.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "TiDB",
        "version": "latest",
        "oracle": "QUERY_PARTITIONING",
        "total_queries": 831460,
        "throughput_qps": 4020,
        "success_rate": 0.83,
        "bugs_found": 2,
        "bug_type": "Logic Bug (HAVING)",
        "observations": "2 bugs: AGG_TO_COP hint + GROUP BY + HAVING.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "TLP WHERE",
        "total_queries": 919218,
        "throughput_qps": 2864,
        "success_rate": 0.99,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 new bugs. Bugs from 2020 fixed.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "TLP AGGREGATE",
        "total_queries": 648505,
        "throughput_qps": 1838,
        "success_rate": 0.43,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. Low success rate.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "TLP HAVING",
        "total_queries": 170172,
        "throughput_qps": 252,
        "success_rate": 0.70,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. Very low throughput.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "TLP GROUP BY",
        "total_queries": 114027,
        "throughput_qps": 268,
        "success_rate": 0.72,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "TLP DISTINCT",
        "total_queries": 100155,
        "throughput_qps": 252,
        "success_rate": 0.71,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs.",
    },
    {
        "experiment": "Exp 2",
        "dbms": "DuckDB",
        "version": "latest",
        "oracle": "NoREC",
        "total_queries": 868119,
        "throughput_qps": 2882,
        "success_rate": 0.99,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "0 bugs. DuckDB mature in 2026.",
    },
    {
        "experiment": "Exp 3",
        "dbms": "SQLite",
        "version": "3.49.1",
        "oracle": "PQS",
        "total_queries": 6344781,
        "throughput_qps": 15641,
        "success_rate": 0.97,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "PQS vs TLP WHERE: TLP WHERE superior (1 bug vs 0).",
    },
    {
        "experiment": "Exp 3",
        "dbms": "MariaDB",
        "version": "latest",
        "oracle": "NoREC",
        "total_queries": 5449445,
        "throughput_qps": 16671,
        "success_rate": 0.95,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "DBMS new to paper. 0 bugs. High throughput.",
    },
    {
        "experiment": "Exp 3",
        "dbms": "MariaDB",
        "version": "latest",
        "oracle": "DQP",
        "total_queries": 34387,
        "throughput_qps": 116,
        "success_rate": 0.99,
        "bugs_found": 0,
        "bug_type": None,
        "observations": "DQP: throughput very low (~116 q/s). 0 bugs.",
    },
]


async def seed_database():
    await init_db()

    async with async_session() as session:
        result = await session.execute(select(StaticResult))
        if result.scalars().first():
            print("Database already seeded. Skipping.")
            return

        for item in SEED_DATA:
            session.add(StaticResult(**item))

        await session.commit()
        print(f"Seeded {len(SEED_DATA)} results into database.")


if __name__ == "__main__":
    asyncio.run(seed_database())